import rawManifest from "@/public/manifest.json";

export type PhotoEntry = { file: string; src: string };
export type GalleryEntry = { file: string; src: string; type: string };

export type Manifest = {
  generatedAt: string;
  gallery: GalleryEntry[];
  girl: PhotoEntry[];
  boy: PhotoEntry[];
  officer: PhotoEntry[];
  adviser: PhotoEntry[];
  queen: PhotoEntry[];
  palaban: PhotoEntry[];
};

/**
 * manifest.json is regenerated by scripts/generate-manifest.js before every
 * build/dev run by scanning public/. Whenever one of the photo folders
 * (e.g. public/queen, public/palaban) happens to be empty at build time,
 * its array in the raw JSON is `[]`, and TypeScript would otherwise infer
 * that array's element type as `never` -- which breaks `manifest.queen[0]?.src`
 * with "Property 'src' does not exist on type 'never'".
 *
 * Casting through this explicit Manifest type fixes that permanently: every
 * field always has a known shape, whether the matching folder currently has
 * 0 photos or 400.
 */
const manifest = rawManifest as Manifest;

export default manifest;
